
all:
	pdflatex ActiveSubspaceKineticsPaper
	bibtex ActiveSubspaceKineticsPaper
	pdflatex ActiveSubspaceKineticsPaper
	pdflatex ActiveSubspaceKineticsPaper

clean:
	rm -f *.aux *.log *.bbl *.blg *.pdf *.out *.thm *.spl
        

